### ISSUE TITLE
Resolving existing files

### ISSUE THREAD

**Issue by miraage** [webpack-contrib/less-loader#103]
Using `webpack-dev-server`, serving from `http://localhost:8080/`;

``` less
.layout {
    background: url(/foo/bar.png) no-repeat center center;
}
```

`http://localhost:8080/foo/bar.png` provides real image, but it's not loaded in styles.
What I do wrong?
