### ISSUE TITLE
.transition is not defined?

### ISSUE THREAD

**Issue by tommck** [webpack-contrib/less-loader#150]
I can't figure out where this problem is coming from.  Can someone help?

Here is my loader config:
```js
{
    test: /\.less$/,
    use: ['style-loader', { loader: 'css-loader', options: { importLoaders: 1 } }, 'less-loader']
}
```

TypeScript statement:
```ts
import './foo.less';
```

foo.less:
```less
.no-touch{
 .modal{
    .btn-close{

      .transition(background-color 0.15s ease-in-out);

      &:hover, &:focus{
        background-color: lighten(@storm, 10%, relative);
      }

      &:active{
        background-color: @storm;
      }

    }
  }
}
```

The error I get is: 

    ERROR in ./~/css-loader?{"importLoaders":1}!./~/less-loader!./src/foo.less
    Module build failed: .transition is undefined
