### ISSUE TITLE
globalVars with paths

### ISSUE THREAD

**Issue by pixelass** [webpack-contrib/less-loader#203]
I have experienced a strange issue with `globalVars` and `modifyVars` when using paths.

**The Less configuration**

```js
const options = {
    globalVars: {
        foobar: 'foobar',
        iWork: 'I work',
        assets: '../../assets'
    }
}
```

**The Less**

```less
.test {
	color: @foobar;
	content: @iWork;
	content: @assets;
	// or content: `@{assets}`;
	// or content: '@{assets}';
}
```

**The error**

```
Module build failed: 
    
    	content: @iWork;
    	content: @assets;
            ^
    Variable @assets is undefined
```

**The CSS output**

```css
@assets : ../../assets;
body {
  min-height: 100%;
  margin: 0; 
 /* ... */ 
}
```

Something seems off when using a path in general. I should be able to pass the string to any property without it causing an error.

**There is a workaround**  

```
assets: '\"../../assets\"'
```

I'm sure if this is actually a Less.js issue or related to this loader.
