### ISSUE TITLE
Class name interpolation with a variable

### ISSUE THREAD

**Issue by otroboe** [webpack-contrib/less-loader#256]
Hello guys !
I have an issue when I'm trying to use a variable to compose a class name. I'm not sure where I'm wrong, it seems quite simple.

* Operating System: `Ubuntu 17.10`
* Node Version: `8.11.1`
* NPM Version: `5.8.0`
* webpack Version: `4.6.0`
* less-loader Version:`4.1.0`

This issue is for a:
- [X] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code

```less
@myvar: "test";

.@{myvar}-button {
  color: red;
}
```

##### webpack.config.js
```js
  module: {
    rules: [
      { test: /\.(ts|tsx)?$/, loader: 'ts-loader' },
      { test: /\.js$/, loader: 'source-map-loader', enforce: 'pre' },
      { test: /\.css$/, use: ['style-loader', 'css-loader'] },
      { test: /\.(woff|woff2|eot|ttf)$/, loader: 'file-loader' },
      { test: /\.less$/, use: ['style-loader', 'css-loader', 'less-loader'] },
    ],
  },
```

### Expected Behavior
```css
.test-button {
  color: red;
}
```

### Actual Behavior
```css
."test"-button {
  color: red;
}
```

**Comment by evilebottnawi** [comment]
Because `less` compile this into:
```css
."test"-button {
  color: red;
}
```

You can try this without the loader, just using `less`, it is more feature than bug and should be reported in `less` repo
