### ISSUE TITLE
Source maps are not working when using style-loader despite using sourceMap: true

### ISSUE THREAD

**Issue by Urik** [webpack-contrib/less-loader#262]
* Operating System: Ubuntu 16.04
* Node Version: 8.9.1
* NPM Version: 6.0
* webpack Version: 4.8.1
* less-loader Version: 4.1.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### webpack.config.js

https://gist.github.com/Urik/d5e5d4d8081b2a5268690fb3e9a1f335

index.js  
```js
import './index.less';
const test = () => console.log('lala'); //Making sure I'm bein run.

test();
```

```less
.test {
    .subTest {
        height: 400px;
        width: 300px;
        background-color: green;
        background-image: url("./350x150.png");
    }
}
```
### Expected Behavior
Chrome should display the original less code. 

### Actual Behavior
Chrome displays the following generated code in the sources tab after clicking on the file path of the css rule link when inspecting the div with the subTest class in the Elements tab:  
```less
.test .subTest {
  height: 400px;
  width: 300px;
  background-color: green;
  background-image: url("350x150.png");
}
```
Please keep in mind, I've tried switching to using sass-loader instead of less-loader and that solves the issue, so it should be something about less-loader.
