### ISSUE TITLE
how to resolve inline javascript using in older less files

### ISSUE THREAD

**Issue by X-neuron** [webpack-contrib/less-loader#350]
we using antd design pro, update to latested loader , then bunble errors.
```
 {
            loader: 'less-loader', 
            options: {
                javascriptEnabled: true 
            }
          }
}
```
without support the  javascriptEnabled, can you suggest another way to resolve the matters? 
thanks much

**Comment by cap-Bernardito** [comment]
`javascriptEnabled` is deprecated so it is not recommend to use for security reasons

You can use `less` - plugins (http://lesscss.org/features/#plugin-atrules-feature) instead.

But if you really want to, you can enable this option like this:

```less
{
    loader: 'less-loader',
    options: {
        lessOptions: {
            javascriptEnabled: true
        }
    }
}
```
