### ISSUE TITLE
v6 generates different css code

### ISSUE THREAD

**Issue by endbay** [webpack-contrib/less-loader#351]
- Operating System: Windows 10
- Node Version: 12.16.0
- NPM Version: 6.14.4
- webpack Version: 4.43.0
- less-loader Version: 6.0.0

### Less code
```less
@c: .Spinner;

@{c} {
    svg {
        animation: spin 0.5s linear infinite;
    }
}

@keyframes spin {
    from {
        transform: rotate(0deg);
    }
    to {
        transform: rotate(360deg);
    }
}
```

### Expected Behavior
```css
.Spinner svg {
        animation: spin 0.5s linear infinite;
}
```

### Actual Behavior
```css
svg {
        animation: spin 0.5s linear infinite;
}
```

### Code

```js
                {
                    test: /\.less$/,
                    use: [
                        {
                            loader: dev ? 'style-loader' : MiniCssExtractPlugin.loader
                        },
                        {
                            loader: 'css-loader',
                            options: {
                                importLoaders: 1,
                                modules: {
                                    localIdentName: '[local]'
                                }

                            }
                        },
                        {
                            loader: 'postcss-loader',
                            options: {
                                plugins: () => [autoprefixer()]
                            }
                        },
                        {
                            loader: 'less-loader',
                            options: {
                                lessOptions: {
                                    javascriptEnabled: true
                                }
                            }
                        }
                    ]
                },
```

This is just happend after upgrading to less-loader v6. The old v5 version doesn't have this issue.

**Comment by evilebottnawi** [comment]
Can't reproduce, please create reproducible test repo.

Please fill out all fields in the issue template, we have header - `### How Do We Reproduce?` Closing now, I will reopen issue after all field filled, please respect time other developers, thanks

**Comment by rjgotten** [comment]
> @endbay
>This is just happend after upgrading to less-loader v6. The old v5 version doesn't have this issue.

less-loader v6 has a dependency `"less": "^3.11.1"` whereas v5 had a peer dependency `"^2.3.1 || ^3.0.0"` i.e. would use whatever you had installed.

I would call this a definite regression in less-loader and I've already opened up #352 to have less restored as a peer dependency. This is currently also necessary to work around a memory consumption problem in less v3.10 and up.

**Comment by BartWaardenburg** [comment]
I'm having the exact same issue. I'm on the latest `less` version and the latest `less-loader` version, but I'm getting the same results as described by @endbay. So latest `less` version still works with `less-loader` v5 but does not with later versions.

It is the exact same less code as described by @endbay, where I have a root less variable as the container class.

**Comment by rjgotten** [comment]
>It is the exact same less code as described by @endbay, where I have a root less variable as the container class.

And what happens if you instead use:

```less
@c : ~".Spinner";

@{c} {
  svg { /* ... */ }
}
```
