### ISSUE TITLE
Variable @z-index not found

### ISSUE THREAD

**Issue by JooelBks2000** [webpack-contrib/less-loader#427]
I am doing z-index related management work，but when i save ，i found that
![image](https://user-images.githubusercontent.com/44807089/124371528-1c7bd180-dcb5-11eb-86b9-15e38e6d15cf.png)
I found related issues，but can not solve my problem ，and when i use easy-less to complie a less file，it worked，and my improt way is right，i think it is Multi-layer loop to lead this issue，and i use it like this
```
z-index: .teacherZIndexS('popups','kaoqinTooltip')[@z-index];
```
So I can’t solve this problem

- less Version：3.8.1
- webpack Version:4.26.0
- less-loader Version:5.0.0

### Code

```js
            {
                test: /\.(css|less)$/,
                use: [
                    MiniCssExtractPlugin.loader,
                    {
                        loader: 'css-loader',
                        options: {
                            url: (url, res) => {
                                if (url.includes('FZLanTingYuanS-B-GB.TTF')) {
                                    return false;
                                }
                                return true;
                            },
                        },
                    },
                    {
                        loader: 'less-loader',
                    },
                ],
            },
```

```css
._generate-z-value(@layer-list,@name,@length,@first){
    .loop(length(@layer-list));
    .loop(@i) when (@i > 0) {
      .innerZIndex(@layer-list,@i,@name,@length,@first);
      .loop((@i - 1));
    }
    .loop(@i) when (@length = 1) and (@name = extract(extract(@layer-list,@i),1)){
      @z-index: extract(extract(@layer-list, @i), 2);
    }
    .fallback() {
      @z-index: -1;
   }
}

.innerZIndex(@array, @i,@name,@length,@first) when (@length >= 2) and (@first = extract(extract(@layer-list,@i),1)){
    @newArray:extract(@array,@i);
    .loop(length(@newArray));
    .loop(@j) when(@j > 0){
      .loop((@j - 1))
    }
    .loop(@j) when(@name = extract(extract(@newArray,@j),1)){
        @z-index:extract(@newArray,@j+1);
    }
};

.teacherZIndexS(...){
    //@spacing:100;
    @name: extract(@arguments,length(@arguments));
    @first: extract(@arguments,1);
    @length: length((@arguments));
    ._generate-z-value(@teacherMainq,@name,@length,@first);
}
```
