### ISSUE TITLE
Fail to using extend feature from less

### ISSUE THREAD

**Issue by Yunkou** [webpack-contrib/less-loader#61]
I wanna using extend feature , like this:

``` less
.flexBox {
    display: -webkit-flex;
    display: -moz-flex;
    display: -ms-flex;
    display: flex;
}
header {
     .flexBox
}
```

But got error msg like this :

``` shell
Module build failed: ModuleError: CssSyntaxError: 
house-list.less:20:5: Unknown word
header {
    .flexBox;
    ^
```

with my `webpack.config.js`

``` javascript
...
module: {
        loaders: [
            { test: /\.vue$/, loader: vue.withLoaders({
                css: ExtractTextPlugin.extract(
                    "style-loader", "css-loader?sourceMap!less!cssnext-loader")
                }),
            },
            { test: /\.less$/, loader: ExtractTextPlugin.extract(
                "style-loader",'css-loader?sourceMap!less!cssnext-loader')
            },
            { test: /\.css$/, loader: ExtractTextPlugin.extract(
                "style-loader", "css-loader?sourceMap!cssnext-loader")
            },
            { test: /\.(jpg|png|gif)$/, loader: "file-loader?name=images/[hash].[ext]"},
            { test: /\.(html|tpl)$/, loader: 'html-loader' }
        ]
    },
...
```

How would I do this?

**Comment by tsheaff** [comment]
Yes I'm getting a similar error.  The worst part is that `lessc` directly form the command line works perfectly.  Unclear why `less-loader` doesn't work just like `lessc`...

**Comment by josephfinlayson** [comment]
As a quick fix, just use autoprefixer for this kind of stuff. Have you tried setting a mixin, and then calling it? That's working correctly for me

**Comment by frob** [comment]
This doesn't work.

```less
/ The micro clearfix http://nicolasgallagher.com/micro-clearfix-hack/
.clearfix() {
  *zoom:1;

  &:before,
  &:after {
      content:"";
      display:table;
  }
  &:after {
      clear:both;
  }
}

body {
  width: 100%;
  .clearfix;
}
```
