### ISSUE TITLE
Issue with variable interpolation when trying to access variable's value with @@var

### ISSUE THREAD

**Issue by oller** [webpack-contrib/less-loader#82]
I'm trying to build an array of colour variables to easily manage across my application.

Using the following working code:

``` less
//LESS
@red: #f00;
@green: #0f0;
@blue: #00f;

@colors: green, red, blue;

.example {
    .-(@i: length(@colors)) when (@i > 0) {
        @name: extract(@colors, @i);
        &.@{name} {background: @@name}
        .-((@i - 1));
    } .-;
}

//CSS
.example.blue {
  background: #00f;
}
.example.red {
  background: #f00;
}
.example.green {
  background: #0f0;
}

```

[You can view this valid code compiling here](http://less2css.org/#%7B%22less%22%3A%22%40red%3A%20%23f00%3B%5Cn%40green%3A%20%230f0%3B%5Cn%40blue%3A%20%2300f%3B%5Cn%5Cn%40colors%3A%20green%2C%20red%2C%20blue%3B%5Cn%5Cn.example%20%7B%5Cn%20%20%20%20.-%28%40i%3A%20length%28%40colors%29%29%20when%20%28%40i%20%3E%200%29%20%7B%5Cn%20%20%20%20%20%20%20%20%40name%3A%20extract%28%40colors%2C%20%40i%29%3B%5Cn%20%20%20%20%20%20%20%20%26.%40%7Bname%7D%20%7Bbackground%3A%20%40%40name%7D%5Cn%20%20%20%20%20%20%20%20.-%28%28%40i%20-%201%29%29%3B%5Cn%20%20%20%20%7D%20.-%3B%5Cn%7D%22%7D)

However this is throwing an error 

```
ERROR in ./~/css-loader!./~/csslint-loader!./~/less-loader!./app/styles/styleguide.less
Module build failed: variable @[object Object],[object Object] is undefined
 @ /styles/modules/colors.less (line 33, column 4)
 near lines:
   .example_module {
       .for(@colors); .-each(@name) {
           &.@{name} {background: @@name}
 @ ./app/styles/styleguide.less 4:14-172
```

This looks like a problem with interpolation specifically with the `@@var` notation.

Has anyone else encountered this?

Relevant npm list section:

``` bash
├─┬ less@2.6.1
│ │ ├── caseless@0.11.0
├── less-loader@2.2.2
```
