### ISSUE TITLE
problem with resolve relative path witch LESS function

### ISSUE THREAD

**Issue by DragorWW** [webpack-contrib/less-loader#85]
in the folder `/app/el/` exsist file `logo.png`
`./app/el/btn.less`

``` less
@import (reference) "~app/mixin/sprite.less";
.btn {
    .sprite('./logo.png');
}
```

`./app/mixin/sprite.less`

``` less
.sprite(@file, @spriteName: 'sprite') {
    width: image-width(@file);
    height: image-height(@file);
    background: url("@{file}#@{spriteName}");
}
```

error:

``` less
    ERROR in ./~/css-loader?sourceMap!./~/postcss-loader?sourceMap!./~/less-loader?sourceMap!./app/el/btn.less
    Module build failed: error evaluating function `image-width`: './logo.png' wasn't found. Tried - /Users/DragorWW/test-app/app/mixin/logo.png,logo.png
```

if not use mixin in `./app/el/btn.less`, all is well.

``` less
.btn {
    width: image-width('./logo.png');
    height: image-height('./logo.png');
    background: url('./logo.png');
}
```

`webpack.config.js`

``` js
module.exports = {
    context: path.join(__dirname, 'app'),
    module: {
        loaders: [
            {
                test: /\.less$/,
                loader: ExtractTextPlugin.extract('style','css?sourceMap!postcss?sourceMap!less?sourceMap')
            },
            {
                test: /\.(jpe?g|png|gif|svg)$/i,
                loaders: [
                    'url?limit=5000&name=images/[name]-[hash:6].[ext]'
                ]
            },
        ]
    },
    resolve: {
        alias: {
            app: path.join(__dirname, '/app')
        },
    },
    plugins: [
        new ExtractTextPlugin('styles.css'),

    ],
};
```
