### ISSUE TITLE
sourceMap option breaks on "@media" nested rule

### ISSUE THREAD

**Issue by ZorGleH** [webpack-contrib/less-loader#92]
Hi,

I have an issue when building with those options:

``` javascript
{
  test: /\.less$/,
  loader: 'style!css?sourceMap!less?sourceMap'
}
```

and a file containing

``` css
.selector {
  @media (max-width: 800px) {
    color: red;
  }
}
```

When I remove the `?sourceMap` option from less, it work fine and gives me the expected output, which is

``` css
@media (max-width: 800px) {
  .selector {
    color: red;
  }
}
```

Any idea?
Thanks.
